Adjust fetcher for new primary ip pricing format and ignore v6 primary addresses. (fixes #39)
jangraefen/hcloud-pricing-exporter pull request #40
Opened 2022-12-26 14:08 UTC by byReqz

I have adjusted the the fetcher for the new API format. Please consider this blocked until https://github.com/hetznercloud/hcloud-go/pull/222 is resolved.

2022-12-26 16:25 UTC, jangraefen requested changes
Very nice change, thank you so much! 😄
I just made some minor remarks, regarding naming.

2022-12-26 16:25 UTC, jangraefen commented on fetcher/primaryip.go
> +		hourlyPrice, monthlyPrice, err := primaryIP.pricing.PrimaryIP(p.Type, datacenter.Location.Name)
This is the correct change, I guess. I was wondering anyway, why Primary IP prices are based on datacenter and not on location, like everything else. Could you also adopt the `NewPrimaryIP` constructor to reflect that? Currently the Prometheus label is still called "datacenter", which should now be "location", like the others.

2022-12-26 16:25 UTC, jangraefen commented on fetcher/prices.go
>  			for _, pricing := range byType.Pricings {
After I looked at your PR on the hcloud-go repository, this makes sense, but I am actually quit suprised that the `Datacenter` attribute is now actually the location. To me, this is counter-inuitive. I would at least refactor this method to consistently call it location and add a comment why its then set to `p.Datacenter` 🙂.

2022-12-26 17:51 UTC, jangraefen approved these changes
Looks good to me! Thank you for you contributen ❤️.

I subscribed to the issue on the hcloud-go repository and will merge this PR as soon as the base issue is resolved.

2022-12-26 17:59 UTC, byReqz commented
Would it make sense to also merge the individual DC labels at https://github.com/jangraefen/hcloud-pricing-exporter/blob/077338b90e641fb51070864bbba5a2d69d0f0156/fetcher/primaryip.go#L32-L33 
to just be the location? Not sure if thats stylistically in-line with the other stuff.

2022-12-26 19:25 UTC, jangraefen commented
> Would it make sense to also merge the individual DC labels at
> 
> https://github.com/jangraefen/hcloud-pricing-exporter/blob/077338b90e641fb51070864bbba5a2d69d0f0156/fetcher/primaryip.go#L32-L33
> 
> to just be the location? Not sure if thats stylistically in-line with the other stuff.

While it would be possible to create the set of labels once and re-use it in the two calls, personally I don't think it is worth it. I am open for a refactoring though, but it should be the same for all fetchers then.

2022-12-26 19:32 UTC, jangraefen commented
Also letting you know: I added a type label to both floating and primary IPs in a PR here: #41
I will merge it after your PR, to prevent a merge conflict for you 🙂.

2022-12-27 16:26 UTC, byReqz commented
Updated the changes for the new proper `hcloud.PrimaryIPTypePricing.Location` field

2022-12-29 13:45 UTC, merged

2022-12-29 13:45 UTC, jangraefen commented
Thanks for your contribution @byReqz. It is very much appreciated 🙂